spin_manifest_version = 2

[application]
authors = ["Taisuke Yamada <tayamada@akamai.com>"]
description = ""
name = "hello-spin"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-spin"

[component.hello-spin]
source = "dist/hello-spin.wasm"
exclude_files = ["**/node_modules"]
[component.hello-spin.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]