spin_manifest_version = 2

[application]
authors = ["Taisuke Yamada <tayamada@akamai.com>"]
description = ""
name = "hello-llm"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-llm"

[component.hello-llm]
source = "dist/hello-llm.wasm"
exclude_files = ["**/node_modules"]
ai_models = ["llama2-chat"]

[component.hello-llm.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]
