spin_manifest_version = 2

[application]
authors = ["Taisuke Yamada <tayamada@akamai.com>"]
description = ""
name = "hello-sqlite"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "hello-sqlite"

[component.hello-sqlite]
source = "dist/hello-sqlite.wasm"
exclude_files = ["**/node_modules"]
sqlite_databases = ["default"]

[component.hello-sqlite.build]
command = ["npm install", "npm run build"]
watch = ["src/**/*.js"]
